package com.jaytech.saga.commons.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object representing an order request for purchasing a product.
 * When a user intends to purchase a product, this DTO is used to pass the necessary information to the system.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class OrderRequestDto {

    /**
     * The ID of the user placing the order.
     */
    private Integer userId;

    /**
     * The ID of the product being purchased.
     */
    private Integer productId;

    /**
     * The amount of the product being purchased.
     */
    private Integer productPrice;

    /**
     * Order ID will be autogenerated.
     */
    private Integer orderId;
}
